apiVersion: apps/v1
kind: Deployment
metadata:
  name: test111
  labels:
    app: test111
  namespace: testa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test111
  template:
    metadata:
      labels:
        app: test111
    spec:
      containers:
        - name: test111
          image: acrworkflowtest.azurecr.io/test
          ports:
            - containerPort: 8080