apiVersion: v1
kind: Service
metadata:
  name: testapp
  namespace: namespace-workflow-1675259597141
spec:
  type: LoadBalancer
  selector:
    app: testapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80