apiVersion: v1
kind: Service
metadata:
  name: test
  namespace: namespace-workflow-1677518233460
spec:
  type: LoadBalancer
  selector:
    app: test
  ports:
    - protocol: TCP
      port: 3600
      targetPort: 3600