apiVersion: v1
kind: Service
metadata:
  name: test111
  namespace: namespace-workflow-1680494612311
spec:
  type: LoadBalancer
  selector:
    app: test111
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80