apiVersion: v1
kind: Service
metadata:
  name: test
  namespace: namespace-workflow-1677263326698
spec:
  type: LoadBalancer
  selector:
    app: test
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080